name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: >
            🔕 This issue is stale because it has been open for 6 days with no activity.
            Please comment or remove the stale label, or it will be closed in 2 days.
          stale-pr-message: >
            📭 This pull request is stale because it has been open for 6 days with no activity.
            Please comment or remove the stale label, or it will be closed in 2 days.
          days-before-stale: 6
          days-before-close: 2
          stale-issue-label: stale
          stale-pr-label: stale
